# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fad2c8c82ea729303aca41ff7cc168ef"
name = "location-mark-up"
handle = "location-mark-up"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-e64ff943.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
